version: "3.9"

services:
 kitchen:
  build: .
  image: html-kitchen
  hostname: kitchen
  expose:
   - "80"

 nginx:
  image: nginx:latest
  volumes:
   - ./nginx.conf:/etc/nginx/nginx.conf
  depends_on:
   - kitchen
  ports:
   - "80:60000"

networks:
 default:
  driver: bridge
  name: kitchen
